# Chaos Mesh Helm values (Ingress для Dashboard)
# Источник: https://github.com/patsevanton/strimzi-kafka-chaos-testing

chaosDaemon:
  runtime: containerd
  socketPath: /run/containerd/containerd.sock
  env:
    LOG_FORMAT: json

controllerManager:
  env:
    LOG_FORMAT: json

dashboard:
  env:
    LOG_FORMAT: json
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: chaos-dashboard.apatsev.org.ru
        paths:
          - path: /
            pathType: Prefix
    annotations: {}
