chaosDaemon:
  runtime: containerd
  socketPath: /run/containerd/containerd.sock
  # JSON logging format
  env:
    LOG_FORMAT: json
controllerManager:
  # JSON logging format
  env:
    LOG_FORMAT: json
dashboard:
  # JSON logging format
  env:
    LOG_FORMAT: json
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: chaos-dashboard.apatsev.org.ru
        paths:
          - path: /
            pathType: Prefix
    annotations: {}
