# Настройки отправки логов во внешнее хранилище (VictoriaLogs)
remoteWrite:
  - url: http://victoria-logs-cluster-vlinsert.victoria-logs-cluster:9481
    headers:
      # Поля, которые будут проигнорированы и не сохранены в VictoriaLogs
      VL-Ignore-Fields:
        - kubernetes.container_id
        - kubernetes.pod_ip
        - kubernetes.pod_labels.pod-template-hash

# Настройки collector: из каких полей извлекать основное сообщение лога (_msg в VictoriaLogs)
collector:
  msgField:
    - message
    - msg

# Настройки podMonitor для сбора метрик коллектора
podMonitor:
  enabled: true
  # Параметр vm=true создаёт VMPodScrape для сбора метрик коллектора в VictoriaMetrics K8s Stack
  vm: true
