vlselect:
  ingress:
    enabled: true
    hosts:
      - name: victorialogs.apatsev.org.ru
        path:
          - /
        port: http
    ingressClassName: nginx

vlstorage:
  retentionPeriod: 1d
  persistentVolume:
    size: 20Gi
