apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-consumer.fullname" . }}
  labels:
    {{- include "kafka-consumer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.health.port }}
      targetPort: health
      protocol: TCP
      name: http
  selector:
    {{- include "kafka-consumer.selectorLabels" . | nindent 4 }}
